### ISSUE TITLE
Using beforeRouteEnter in global mixins not working

### ISSUE THREAD

**Issue by WhoisUnknown** [vuejs/vue-router#2871]
### Version
3.1.1

### Reproduction link
[https://codesandbox.io/s/vue-template-7z1uq](https://codesandbox.io/s/vue-template-7z1uq)

### Steps to reproduce
1. Create minimal App with vue router.
2. Register global mixin with hook beforeRouterEnter
3. Try to open page

### What is expected?
A working beforeRouterEnter hook in all components in app

### What is actually happening?
Get error in console " TypeError: guard is not a function
    at routeEnterGuard (vue-router.common.js:2242)..."

---
This worked in vue 2.5.21

**Comment by posva** [comment]
Note to myself: there are also merging issues when defining both before guards in component and mixins.

For a global mixin, it makes more sense to use `router.beforeEach` unless you do something in the `next` callback

**Comment by posva** [comment]
It seems that putting the router config in a different file doesn't trigger the error: https://codesandbox.io/embed/vue-template-o57wx

I will have to investigate further

**Comment by WhoisUnknown** [comment]
> Note to myself: there are also merging issues when defining both before guards in component and mixins.
> 
> For a global mixin, it makes more sense to use `router.beforeEach` unless you do something in the `next` callback

I use mutations in `next` callback

**Comment by WhoisUnknown** [comment]
> It seems that putting the router config in a different file doesn't trigger the error: https://codesandbox.io/embed/vue-template-o57wx
> 
> I will have to investigate further


In project we using async compoennts and single file for vue router. Anyway we got this problem

**Comment by janvennemann** [comment]
Just ran into this issue as well. Making sure to apply the mixing after `Vue.use(VueRouter);` should be enough to fix it. This ensures that vue-router sets the correct option merging strategies for `beforeRouterEnter`.
